apiVersion: v1
kind: Service
metadata:
  name: {{ include "epicore.fullname" . }}
  labels:
    {{- include "epicore.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.acmcert }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 600
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if  .Values.service.port}}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
    {{- end }}
    - port: {{ .Values.service.sslport }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "epicore.selectorLabels" . | nindent 4 }}
