apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: get-members
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - sh
            - -c
            - ./jobs.sh getMembers
            image: 503172036736.dkr.ecr.us-east-1.amazonaws.com/epicore-app:90e7ed2
            imagePullPolicy: IfNotPresent
            name: get-members
            resources:
              limits:
                cpu: 1
                memory: 512Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /var/www/html/data
                name: persistent-storage
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 
          volumes:
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: efs-claim
  schedule: 30 1 * * 1
